{% set name = "jax-unirep" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jax_unirep-{{ version }}.tar.gz
  sha256: d1914b79bf434fb91b8fc2623feb791b7ecb250a0a917bb226ecbc3632f72f5e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jax
    - jaxlib
    - multipledispatch
    - numpy
    - optuna
    - python >=3.6
    - scikit-learn
    - tqdm

test:
  imports:
    - jax_unirep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ElArkk/jax-unirep
  summary: A performant and user-friendly reimplementation of UniRep in JAX.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
